name: TinyEmpires
version: ${project.version}
main: dev.sucrose.tinyempires.TinyEmpires
api-version: 1.16
depend: [dynmap]
commands:
  convert:
    description: Convert diamonds to coins
  gift:
    description: Gift coins to player
  pay:
    description: OP - Pay coins to play
  take:
    description: OP - Take coins from player
  empire:
    description: Empire command
    aliases: [e]
  arena:
    description: Hold matches in arenas around the map
  clearcache:
    description: OP - Clear cache for debugging
  dimension:
    description: OP - Teleport to the spawn location of another world
  flyspeed:
    description: OP - Change player flyspeed
  invisible:
    description: OP - Toggle player server invisibility
  smite:
    description: OP - Smite player
  olympus:
    description: OP - Teleport to Olympus
  yggdrasil:
    description: Command for Yggdrasil arena